esperanto\UserBundle\Entity\User:
    type: entity
    table: user_user
    repositoryClass: esperanto\UserBundle\Repository\UserRepository

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        firstName:
            type: string
            length: 255
            nullable: true

        lastName:
            type: string
            length: 255
            nullable: true

    manyToMany:
        groups:
            targetEntity: Group
            inversedBy: users
            joinTable:
                name: user_user_group
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    group_id:
                        referencedColumnName: id

    lifecycleCallbacks: {  }
