esperanto\ProjectBundle\Entity\Content:
    type: entity
    table: project_content

    fields:
        citation:
            type: string
            length: 255
            nullable: true

        author:
          type: string
          length: 255
          nullable: true

        heading:
          type: string
          length: 255
          nullable: true

        text:
            type: text
            nullable: true

        name1:
            type: string
            length: 255
            nullable: true

        street1:
            type: string
            length: 255
            nullable: true

        place1:
            type: string
            length: 255
            nullable: true

        phone1:
            type: string
            length: 255
            nullable: true

        fax1:
            type: string
            length: 255
            nullable: true

        mail1:
            type: string
            length: 255
            nullable: true

        name2:
            type: string
            length: 255
            nullable: true

        street2:
            type: string
            length: 255
            nullable: true

        place2:
            type: string
            length: 255
            nullable: true

        phone2:
            type: string
            length: 255
            nullable: true

        fax2:
            type: string
            length: 255
            nullable: true

        mail2:
            type: string
            length: 255
            nullable: true

    manyToMany:
        file:
            cascade: ['persist', 'refresh']
            targetEntity: esperanto\MediaBundle\Entity\File
            joinTable:
                name: project_content_file
                joinColumns:
                    content_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    file_id:
                        referencedColumnName: id
    lifecycleCallbacks: {  }
