esperanto\ProjectBundle\Entity\Download:
    type: mappedSuperclass
    table: project_download

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        title:
            type: string
            length: 255
            nullable: true

        text:
            type: text
            nullable: true

    manyToMany:
        file:
            cascade: ['persist', 'refresh']
            targetEntity: esperanto\MediaBundle\Entity\File
            joinTable:
                name: project_download_file
                joinColumns:
                    download_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    file_id:
                        referencedColumnName: id

    lifecycleCallbacks: {  }
