parameters:
    esperanto_user.event.user.class: esperanto\UserBundle\EventListener\AdminUserBuilderSubscriber
    esperanto_user.event.group.class: esperanto\UserBundle\EventListener\AdminGroupBuilderSubscriber
    security.authentication.voter.group_role_voter.class: esperanto\UserBundle\Security\Authentication\Voter\GroupRoleVoter
    security.authentication.success_handler.class: esperanto\UserBundle\Security\Authentication\AuthenticationSuccessHandler
    esperanto_user.event.save_user.class: esperanto\UserBundle\EventListener\SaveUserSubscriber

services:
    esperanto_user.event.user:
        class: %esperanto_user.event.user.class%
        tags:
            - { name: kernel.event_subscriber }

    esperanto_user.event.group:
        class: %esperanto_user.event.group.class%
        tags:
            - { name: kernel.event_subscriber }

    esperanto_user.event.save_user:
        class: %esperanto_user.event.save_user.class%
        arguments:
            - @fos_user.user_manager
        tags:
            - { name: kernel.event_subscriber }

    esperanto_user_user:
        class: %esperanto_user.form.type.user.class%
        tags:
            - { name: form.type }

    esperanto_user_group:
        class: %esperanto_user.form.type.group.class%
        tags:
            - { name: form.type }
        arguments:
            - @security.roles.provider

    security.authentication.voter.group_role_voter:
        class:      %security.authentication.voter.group_role_voter.class%
        public:     false
        tags:
            - { name: security.voter }