esperanto\SettingBundle\Entity\Setting:
    type: mappedSuperclass
    table: setting_setting
    repositoryClass: esperanto\SettingBundle\Repository\SettingRepository

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255

        container:
            type: blob
            nullable: true

    lifecycleCallbacks: {  }
