imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enabled: true, enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - 'esperantoAdminBundle:Form:fields.html.twig'
            - 'esperantoContentBundle:Form:fields.html.twig'
            - 'esperantoCategoryBundle:Form:fields.html.twig'
            - 'esperantoMediaBundle:Form:fields.html.twig'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ 'esperantoAdminBundle' ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        jsminplus: ~
        cssmin: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: smtp
    host:      w012aa15.kasserver.com
    username:  m031179a
    password:  MkzR8AUEBLrgYEFx


stof_doctrine_extensions:
    orm:
        default:
            sluggable: true
            timestampable: true

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: esperanto\UserBundle\Entity\User
    group:
        group_class: esperanto\UserBundle\Entity\Group

liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~
        news_thumb:
            quality: 75
            filters:
                thumbnail: { size: [300, 110], mode: outbound }



esperanto_page:
    classes:
        page:
            model: esperanto\ProjectBundle\Entity\Content
            form: esperanto\ProjectBundle\Form\Type\ContentType
            repository: esperanto\ProjectBundle\Repository\ContentRepository

esperanto_project:
    classes:
        appointment:
            model: esperanto\ProjectBundle\Entity\Appointment
            form: esperanto\ProjectBundle\Form\Type\AppointmentType
            repository: esperanto\ProjectBundle\Repository\AppointmentRepository
        download:
            model: esperanto\ProjectBundle\Entity\Download
            form: esperanto\ProjectBundle\Form\Type\DownloadType
            repository: esperanto\ProjectBundle\Repository\DownloadRepository