esperanto\CategoryBundle\Entity\Collection:
    type: entity
    table: category_collection
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        name:
            type: string
            length: 255
            nullable: true

    oneToMany:
        categories:
            mappedBy: collection
            targetEntity: Category
            cascade: ['persist', 'refresh', 'remove']

    lifecycleCallbacks: {  }
