esperanto\SliderBundle\Entity\Slider:
    type: mappedSuperclass
    table: slider_slider
    repositoryClass: esperanto\SliderBundle\Repository\SliderRepository

    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
            nullable: true

        text:
            type: text
            nullable: true

        url:
            type: text
            length: 255
            nullable: true

        link_type:
            type: text
            length: 255
            nullable: true

        order:
            type: integer