parameters:
    esperanto_admin.twig.admin_menu_render.class: esperanto\AdminBundle\Twig\AdminMenuRender
    esperanto_admin.twig.admin_menu_render.template: 'esperantoAdminBundle:View:menu.html.twig'

    esperanto_admin.twig.tab_render.class: esperanto\AdminBundle\Twig\TabRender
    esperanto_admin.twig.tab_render.template: 'esperantoAdminBundle:View:tab.html.twig'

    esperanto_admin.twig.pagination_render.class: esperanto\AdminBundle\Twig\PaginationRender
    esperanto_admin.twig.pagination_render.template: 'esperantoAdminBundle:View:pagination.html.twig'

services:
    esperanto_admin.twig.admin_menu_render:
        class: %esperanto_admin.twig.admin_menu_render.class%
        arguments:
            - '@service_container'
            - '%esperanto_admin.twig.admin_menu_render.template%'
        tags:
            - { name: twig.extension }

    esperanto_admin.twig.tab_render:
        class: %esperanto_admin.twig.tab_render.class%
        arguments:
            - %esperanto_admin.twig.tab_render.template%
        tags:
            - { name: twig.extension }

    esperanto_admin.twig.pagination_render:
        class: %esperanto_admin.twig.pagination_render.class%
        arguments:
            - %esperanto_admin.twig.pagination_render.template%
        tags:
            - { name: twig.extension }