parameters:
#    esperanto_assets.example.class: esperanto\AssetsBundle\Example

services:
#    esperanto_assets.example:
#        class: %esperanto_assets.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
