parameters:
    esperanto_category.event.collection.class: esperanto\CategoryBundle\EventListener\AdminBuilderSubscriber
    esperanto_category.form.collection.class: esperanto\CategoryBundle\Form\Type\CollectionType
    esperanto_category_manager.class: esperanto\CategoryBundle\Form\Type\CollectionType
    esperanto_category.class: esperanto\CategoryBundle\Form\Type\CategoryEntityType

services:
    esperanto_category.event.collection:
        class: %esperanto_category.event.collection.class%
        tags:
            - { name: 'kernel.event_subscriber' }

    esperanto_category_collection:
        class: %esperanto_category.form.collection.class%
        tags:
            - { name: form.type }

    esperanto_category:
        class: %esperanto_category.class%
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: form.type, alias: 'esperanto_category'}

    esperanto_category_manager:
        class: %esperanto_category_manager.class%